<?php
return [
    [
        'id' => 'de',
        'title' => 'Германия 🇩🇪',
        'domain' => 'de.magicv.ru',
        'port' => 443,
        'ssh_host' => '77.239.127.142',
        'ssh_user' => 'xraybot',
        'ssh_key_path' => '/var/www/magicvpn/.ssh/id_ed25519',
        'xray_config_path' => '/usr/local/etc/xray/config.json',
		'provision_mode' => 'api',
		'xray_api_server' => '127.0.0.1:10085',
		'xray_api_tag' => 'api',
		'xray_binary' => 'xray',
		'xray_reload_cmd' => 'true',
        'transport' => 'reality',
        'inbound_tag' => 'vless-reality',
        'reality_public_key' => '--H9CyOJjEGMGYPEFr-xXI8SbacGkcZLDuG2JxG85VA',
        'reality_short_id' => '313f3d6a3b1f5b40',
        'reality_server_name' => 'www.ebay.com',
        'reality_fp' => 'edge',
        'reality_flow' => '',
        'reality_spx' => '/'
/*         'profiles' => [
            [
                'id' => 'de_443',
                'title' => 'Германия 🇩🇪 Main',
                'domain' => 'de.magicv.ru',
                'port' => 443,
                'ssh_host' => '77.239.127.142',
                'ssh_user' => 'xraybot',
                'ssh_key_path' => '/var/www/magicvpn/.ssh/id_ed25519',
                'xray_config_path' => '/usr/local/etc/xray/config.json',
				'provision_mode' => 'api',
				'xray_api_server' => '127.0.0.1:10085',
				'xray_api_tag' => 'api',
				'xray_binary' => 'xray',
				'xray_reload_cmd' => 'true',
                'transport' => 'reality',
                'inbound_tag' => 'vless-reality',
                'reality_public_key' => '--H9CyOJjEGMGYPEFr-xXI8SbacGkcZLDuG2JxG85VA',
                'reality_short_id' => '313f3d6a3b1f5b40',
                'reality_server_name' => 'www.ebay.com',
                'reality_fp' => 'chrome',
                'reality_flow' => '',
                'reality_spx' => '/',
            ],
            [
                'id' => 'de_2053',
                'title' => 'Германия 🇩🇪 Stable',
                'domain' => 'de.magicv.ru',
                'port' => 2053,
                'ssh_host' => '77.239.127.142',
                'ssh_user' => 'xraybot',
                'ssh_key_path' => '/var/www/magicvpn/.ssh/id_ed25519',
                'xray_config_path' => '/usr/local/etc/xray/config.json',
				'provision_mode' => 'api',
				'xray_api_server' => '127.0.0.1:10085',
				'xray_api_tag' => 'api',
				'xray_binary' => 'xray',
				'xray_reload_cmd' => 'true',
                'transport' => 'reality',
                'inbound_tag' => 'vless-reality-mc-2053',
                'reality_public_key' => '--H9CyOJjEGMGYPEFr-xXI8SbacGkcZLDuG2JxG85VA',
                'reality_short_id' => '4a4a2288da7ecacd',
                'reality_server_name' => 'www.microsoft.com',
                'reality_fp' => 'chrome',
                'reality_flow' => '',
                'reality_spx' => '/',
            ],
            [
                'id' => 'de_8443',
                'title' => 'Германия 🇩🇪 Backup',
                'domain' => 'de.magicv.ru',
                'port' => 8443,
                'ssh_host' => '77.239.127.142',
                'ssh_user' => 'xraybot',
                'ssh_key_path' => '/var/www/magicvpn/.ssh/id_ed25519',
                'xray_config_path' => '/usr/local/etc/xray/config.json',
				'provision_mode' => 'api',
				'xray_api_server' => '127.0.0.1:10085',
				'xray_api_tag' => 'api',
				'xray_binary' => 'xray',
				'xray_reload_cmd' => 'true',
                'transport' => 'reality',
                'inbound_tag' => 'vless-reality-apple-8443',
                'reality_public_key' => '--H9CyOJjEGMGYPEFr-xXI8SbacGkcZLDuG2JxG85VA',
                'reality_short_id' => 'e1a7e5382cbd81f8',
                'reality_server_name' => 'www.apple.com',
                'reality_fp' => 'chrome',
                'reality_flow' => '',
                'reality_spx' => '/',
            ],
        ], */
    ],
    [
        'id' => 'fr',
        'title' => 'Франция 🇫🇷',
        'domain' => 'fr.magicv.ru',
        'port' => 443,
        'ssh_host' => '144.31.214.200',
        'ssh_user' => 'xraybot',
        'ssh_key_path' => '/var/www/magicvpn/.ssh/id_ed25519',
        'xray_config_path' => '/usr/local/etc/xray/config.json',
		'provision_mode' => 'api',
		'xray_api_server' => '127.0.0.1:10085',
		'xray_api_tag' => 'api',
		'xray_binary' => 'xray',
		'xray_reload_cmd' => 'true',
        'transport' => 'reality',
        'inbound_tag' => 'vless-reality',
        'reality_public_key' => 'LaKURKu6W8WGaYThiDSHl4EXdeh_h0iXUsJc0-eFDGw',
        'reality_short_id' => 'f483f9c3e1f9f1c6',
        'reality_server_name' => 'www.microsoft.com',
        'reality_fp' => 'edge',
        'reality_flow' => '',
        'reality_spx' => '/',
    ],
];
